export const SET_SIGN_DIALOG_OPEN = 'SET_SIGN_DIALOG_OPEN';
export const SET_SIGN_DIALOG_CLOSE = 'SET_SIGN_DIALOG_CLOSE';
export const SET_SIGN_DIALOG_LOGIN = 'SET_SIGN_DIALOG_LOGIN';
export const SET_SIGN_DIALOG_REGISTER = 'SET_SIGN_DIALOG_REGISTER';

export const EMAIL_FOUND = 'EMAIL_FOUND';
export const EMAIL_ERROR = 'EMAIL_ERROR';
